### PR TITLE
Test Apache ORC 1.9.3 RC0

### PR DESCRIPTION
**Pull request by wgtmac**

### CODE REVIEW

**Comment by wgtmac** [comment]
```
* What went wrong:
Execution failed for task ':iceberg-spark:iceberg-spark-runtime-3.5_2.12:shadowJar'.
> Unsupported class file major version 65
```

Is this expected? @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
> Unsupported class file major version 65

No, it means Java 21 built class files.

Apache ORC `branch-1.9` uses Java 8 to publish. Here is the link.
- https://github.com/apache/orc/actions/runs/8313026964/job/22748559751

Which class file does it complain, @wgtmac ?

**Comment by wgtmac** [comment]
> Which class file does it complain, @wgtmac ?

I cannot see any evidence of a specific class file from https://github.com/wgtmac/iceberg/actions/runs/8314394220/job/22751510949?pr=10

**Comment by dongjoon-hyun** [comment]
FYI, the following was Apache ORC 1.9.2 release and previous Iceberg test. I'm not tracking Apache Iceberg community after that. You may ask Iceberg community, @wgtmac .

- https://github.com/apache/orc/issues/1647
- https://github.com/dongjoon-hyun/iceberg/pull/16

**Comment by wgtmac** [comment]
Let me close this as 1.9.2 was tested against Apache Iceberg 1.5.x

**Pull request closed without merging**
